---
# tasks file for tomcat_setup_check

- name: install the latest version of Docker
  shell:
      sudo yum install -y yum-utils && sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

- name: Start & Enable docker
  systemd:
      name: docker
      state: started
      enabled: true
